<?php

/**
 * @file
 * Code for Theme Switcher module.
 */

/**
 * Implements hook_page_bottom().
 *
 * Adds theme switcher form to the bottom of the page.
 */
function themeswitcher_page_bottom(&$page_bottom) {
  $page_bottom['themeswitcher'] = \Drupal::formBuilder()->getForm('Drupal\themeswitcher\Form\ThemeSwitcherForm');
  $page_bottom['#access'] = \Drupal::currentUser()->hasPermission('choose preferred theme');
}
